import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'signaling_service.dart';
import '../webrtc_service.dart';

/// Single unified call state model.
enum CallState {
  idle,
  calling,
  ringing,
  connecting,
  connected,
  ended,
}

/// Central controller and single owner of active call state and WebRTC lifecycle.
class CallController extends ChangeNotifier {
  final SignalingService signalingService;
  final WebRTCService webrtcService;

  CallState _state = CallState.idle;
  String? _currentCallId;
  String? _otherUserId;
  String? _otherUserName;
  String? _lastFailureReason;
  DateTime? _callStartTime;
  bool _isReceiver = false;
  StreamSubscription<Map<String, dynamic>>? _signalingSub;

  CallController({
    required this.signalingService,
    required this.webrtcService,
  }) {
    _initListeners();
  }

  CallState get state => _state;
  String? get currentCallId => _currentCallId;
  String? get otherUserId => _otherUserId;
  String? get otherUserName => _otherUserName;
  String? get lastFailureReason => _lastFailureReason;
  DateTime? get callStartTime => _callStartTime;
  bool get isReceiver => _isReceiver;

  bool get isMuted => webrtcService.isMuted;
  bool get isSpeakerOn => webrtcService.isSpeakerOn;

  void _initListeners() {
    // Listen to incoming signaling messages
    _signalingSub?.cancel();
    _signalingSub = signalingService.messageStream.listen(_handleSignalingMessage);

    // Listen to local WebRTC candidates generated by flutter_webrtc
    webrtcService.onLocalCandidate = (candidate) {
      if (_currentCallId != null && _otherUserId != null) {
        debugPrint('[CallController SEND] ice_candidate for call $_currentCallId');
        signalingService.send({
          'type': 'ice_candidate',
          'call_id': _currentCallId,
          'to_user_id': _otherUserId,
          'candidate': {
            'candidate': candidate.candidate,
            'sdpMid': candidate.sdpMid,
            'sdpMLineIndex': candidate.sdpMLineIndex,
          },
        });
      }
    };

    // Listen to WebRTC connection state changes
    webrtcService.onConnectionState = (connState) {
      debugPrint('[CallController] WebRTC connection state -> $connState');
      if (connState == RTCPeerConnectionState.RTCPeerConnectionStateConnected) {
        _callStartTime ??= DateTime.now();
        _setState(CallState.connected);
      } else if (connState == RTCPeerConnectionState.RTCPeerConnectionStateDisconnected) {
        // Disconnected can be temporary (transient network jitter or negotiation phase).
        // Log the state, keep the call alive, do NOT send call_ended, do NOT destroy PeerConnection.
        debugPrint('[CallController] WebRTC connection state is Disconnected (transient). Keeping call alive.');
      } else if (connState == RTCPeerConnectionState.RTCPeerConnectionStateFailed) {
        // Genuine WebRTC connection failure: cleanly end the call
        debugPrint('[CallController] WebRTC connection Failed. Ending call.');
        _lastFailureReason = 'WebRTC connection failed';
        endCall();
      } else if (connState == RTCPeerConnectionState.RTCPeerConnectionStateClosed) {
        debugPrint('[CallController] WebRTC peer connection closed.');
        if (_state != CallState.idle && _state != CallState.ended) {
          _cleanupSession();
          _setState(CallState.idle);
        }
      }
    };

    // If signaling drops during an active call, cleanly tear down
    signalingService.addListener(_handleSignalingConnectionChange);
  }

  void _handleSignalingConnectionChange() {
    if (!signalingService.isConnected &&
        (_state != CallState.idle && _state != CallState.ended)) {
      debugPrint('[CallController] Signaling socket lost during active call. Cleaning up.');
      _lastFailureReason = 'Signaling disconnected';
      endCall();
    }
  }

  void _setState(CallState newState) {
    if (_state != newState) {
      debugPrint('[CallController STATE] $_state -> $newState');
      _state = newState;
      notifyListeners();
    }
  }

  /// Initiates an outgoing call to [targetUserId].
  /// Sends `call_request` with NO local call_id (backend generates authoritative call_id).
  void startCall(String targetUserId, String targetUserName) {
    if (!signalingService.isConnected) {
      _lastFailureReason = 'Not connected to server';
      _setState(CallState.ended);
      return;
    }

    if (_state != CallState.idle) {
      debugPrint('[CallController] Resetting call state before starting new call (was: $_state)');
      resetCallState();
    }

    _otherUserId = targetUserId.trim();
    _otherUserName = targetUserName.trim();
    _currentCallId = null; // Awaiting backend authoritative call_id
    _lastFailureReason = null;
    _callStartTime = null;
    _isReceiver = false;

    _setState(CallState.calling);

    debugPrint('[CallController] Sending call_request to $_otherUserId...');
    signalingService.send({
      'type': 'call_request',
      'to_user_id': _otherUserId,
    });
  }

  /// Accepts an incoming call.
  /// Sends `call_accepted` using the backend's authoritative [currentCallId],
  /// transitions to [CallState.connecting], initializes WebRTC, and awaits remote offer.
  Future<void> acceptCall() async {
    if (_currentCallId == null || _currentCallId!.isEmpty || _otherUserId == null) {
      debugPrint('[CallController ERROR] Cannot accept call: missing call_id or caller');
      return;
    }

    debugPrint('[CallController] Accepting call $_currentCallId from $_otherUserId...');
    signalingService.send({
      'type': 'call_accepted',
      'call_id': _currentCallId,
      'to_user_id': _otherUserId,
    });

    _setState(CallState.connecting);

    try {
      await webrtcService.initializePeerConnection();
    } catch (e) {
      debugPrint('[CallController ERROR] Error initializing WebRTC on accept: $e');
      endCall();
    }
  }

  /// Rejects an incoming call.
  void rejectCall() {
    final callId = _currentCallId;
    final otherUserId = _otherUserId;
    if (otherUserId != null && otherUserId.isNotEmpty) {
      debugPrint('[CallController] Rejecting call $callId from $otherUserId...');
      final payload = <String, dynamic>{
        'type': 'call_rejected',
        'to_user_id': otherUserId,
      };
      if (callId != null && callId.isNotEmpty) {
        payload['call_id'] = callId;
      }
      signalingService.send(payload);
    }
    _cleanupSession();
    _setState(CallState.idle);
  }

  /// Ends an active or pending call cleanly.
  Future<void> endCall() async {
    final callId = _currentCallId;
    final otherUserId = _otherUserId;

    if (otherUserId != null && otherUserId.isNotEmpty) {
      debugPrint('[CallController] Ending call $callId with $otherUserId...');
      final payload = <String, dynamic>{
        'type': 'call_ended',
        'to_user_id': otherUserId,
      };
      if (callId != null && callId.isNotEmpty) {
        payload['call_id'] = callId;
      }
      signalingService.send(payload);
    }

    await webrtcService.endCall();
    _cleanupSession();
    _setState(CallState.idle);
  }

  /// Resets call state to idle without leaving active server state.
  void resetCallState() {
    final callId = _currentCallId;
    final otherUserId = _otherUserId;
    if (otherUserId != null && otherUserId.isNotEmpty) {
      final payload = <String, dynamic>{
        'type': 'call_ended',
        'to_user_id': otherUserId,
      };
      if (callId != null && callId.isNotEmpty) {
        payload['call_id'] = callId;
      }
      signalingService.send(payload);
    }
    webrtcService.endCall();
    _cleanupSession();
    _setState(CallState.idle);
  }

  void _cleanupSession() {
    _currentCallId = null;
    _otherUserId = null;
    _otherUserName = null;
    _callStartTime = null;
    _isReceiver = false;
  }

  void toggleMute() {
    webrtcService.toggleMute();
    notifyListeners();
  }

  Future<void> setSpeaker(bool enabled) async {
    await webrtcService.setSpeaker(enabled);
    notifyListeners();
  }

  Future<void> _handleSignalingMessage(Map<String, dynamic> data) async {
    final String? type = data['type'] as String?;
    if (type == null) return;

    debugPrint('[CallController RECV]: type=$type');

    switch (type) {
      case 'call_started':
        final callId = data['call_id']?.toString();
        final toUserId = data['to_user_id']?.toString();
        if (_state == CallState.idle || _state == CallState.ended) {
          // Caller already cancelled before call_started arrived! Send call_ended immediately so backend and callee clear the call.
          if (callId != null && callId.isNotEmpty) {
            signalingService.send({
              'type': 'call_ended',
              'call_id': callId,
              if (toUserId != null && toUserId.isNotEmpty) 'to_user_id': toUserId,
            });
          }
          break;
        }
        if (callId != null && callId.isNotEmpty) {
          _currentCallId = callId;
        }
        if (toUserId != null && toUserId.isNotEmpty && (_otherUserId == null || _otherUserId!.isEmpty)) {
          _otherUserId = toUserId;
        }
        debugPrint('[CallController RECV] call_started with authoritative call_id: $_currentCallId');
        break;

      case 'incoming_call':
        // Receiver receives incoming call from backend
        final callId = (data['call_id'] ?? '').toString();
        final fromUserId = (data['from_user_id'] ?? data['caller_id'] ?? '').toString();
        final callerName = (data['caller_name'] ??
                data['callerName'] ??
                data['from_name'] ??
                fromUserId)
            .toString();

        if (callId.isNotEmpty) {
          _currentCallId = callId;
        }
        _otherUserId = fromUserId;
        _otherUserName = callerName;
        _lastFailureReason = null;
        _callStartTime = null;
        _isReceiver = true;

        _setState(CallState.ringing);
        break;

      case 'call_accepted':
        // Caller receives call_accepted containing authoritative call_id
        final callId = (data['call_id'] ?? _currentCallId ?? '').toString();
        if (callId.isNotEmpty) {
          _currentCallId = callId;
        }

        _setState(CallState.connecting);

        // As Caller: initialize WebRTC, create SDP offer, and send it
        try {
          await webrtcService.initializePeerConnection();
          final offerSdp = await webrtcService.createOffer();
          debugPrint('[CallController SEND] offer for call $_currentCallId');
          signalingService.send({
            'type': 'offer',
            'call_id': _currentCallId,
            'to_user_id': _otherUserId,
            'sdp': offerSdp,
          });
        } catch (e) {
          debugPrint('[CallController ERROR] Error creating offer: $e');
          endCall();
        }
        break;

      case 'call_rejected':
        _lastFailureReason = 'Call was rejected';
        await webrtcService.endCall();
        _cleanupSession();
        _setState(CallState.ended);
        break;

      case 'call_failed':
        final reason = (data['reason'] ?? 'call_failed').toString();
        _lastFailureReason = (reason == 'offline')
            ? 'User is offline'
            : (reason == 'busy')
                ? 'User is busy'
                : reason;
        debugPrint('[CallController] Call failed: $_lastFailureReason');
        await webrtcService.endCall();
        _cleanupSession();
        _setState(CallState.ended);
        break;

      case 'call_ended':
        final incomingCallId = data['call_id']?.toString();
        if (_currentCallId != null &&
            _currentCallId!.isNotEmpty &&
            incomingCallId != null &&
            incomingCallId.isNotEmpty &&
            incomingCallId != _currentCallId) {
          debugPrint('[CallController] Ignoring call_ended for different call_id: $incomingCallId (current: $_currentCallId)');
          break;
        }

        debugPrint('[CallController] Remote peer ended call $_currentCallId');
        _lastFailureReason = data['reason']?.toString() ?? 'Call ended by remote peer';
        await webrtcService.endCall();
        _cleanupSession();
        _setState(CallState.ended);
        break;

      case 'offer':
        // Receiver handles SDP offer and creates SDP answer
        final String sdp = (data['sdp'] ?? data['description']?['sdp']) as String;
        try {
          if (webrtcService.peerConnection == null) {
            await webrtcService.initializePeerConnection();
          }
          final answerSdp = await webrtcService.handleOfferAndCreateAnswer(sdp);
          debugPrint('[CallController SEND] answer for call $_currentCallId');
          signalingService.send({
            'type': 'answer',
            'call_id': _currentCallId,
            'to_user_id': _otherUserId,
            'sdp': answerSdp,
          });
        } catch (e) {
          debugPrint('[CallController ERROR] Error handling offer: $e');
        }
        break;

      case 'answer':
        // Caller handles SDP answer
        final String sdp = (data['sdp'] ?? data['description']?['sdp']) as String;
        try {
          await webrtcService.handleAnswer(sdp);
        } catch (e) {
          debugPrint('[CallController ERROR] Error handling answer: $e');
        }
        break;

      case 'ice_candidate':
      case 'ice-candidate':
        // Remote ICE candidate received
        final dynamic candPayload = data['candidate'];
        if (candPayload is Map) {
          final candidateStr = candPayload['candidate'] as String?;
          final sdpMid = candPayload['sdpMid'] as String?;
          final sdpMLineIndex = candPayload['sdpMLineIndex'] as int?;
          if (candidateStr != null && candidateStr.isNotEmpty) {
            await webrtcService.addRemoteCandidate(
              RTCIceCandidate(candidateStr, sdpMid, sdpMLineIndex),
            );
          }
        } else if (candPayload is String && candPayload.isNotEmpty) {
          await webrtcService.addRemoteCandidate(
            RTCIceCandidate(
              candPayload,
              data['sdpMid'] as String?,
              data['sdpMLineIndex'] as int?,
            ),
          );
        }
        break;

      default:
        break;
    }
  }

  bool _isDisposed = false;

  @override
  void notifyListeners() {
    if (!_isDisposed) {
      super.notifyListeners();
    }
  }

  @override
  void dispose() {
    _isDisposed = true;
    signalingService.removeListener(_handleSignalingConnectionChange);
    _signalingSub?.cancel();
    super.dispose();
  }
}
